# Creates PRs for dependencies that can be updated
# in a Deno project using Molt.
# - https://github.com/hasundue/molt
# - https://github.com/hasundue/molt-action

on:
  workflow_dispatch:
  schedule:
    # Run twice a month (1st and 15th) at 0:00 (12:00AM or Midnight, UTC)
    # See POSIX cron syntax visualized at https://crontab.guru/#0_0_1,15_*_*
    # GitHub Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    # Cron syntax reference: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: "0 0 1,15 * *"

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check dependencies
        uses: hasundue/molt-action@v1
        with:
          commit-prefix: "deps: "
